POST http://localhost:1234/user
Content-Type: application/json

{
  "urlhost": "http://127.0.0.1:1234/",
  "user": "Alejandro",
  "email": "emiliocube16j@gmail.com",
  "phone": 912908843,
  "pass": "Diqwer63528"
}
