POST http://localhost:4000/user
Content-Type: application/json

{
  "urlhost": "http://127.0.0.1:4000/",
  "user": "Vicki",
  "email": "holiboli@gmail.com",
  "phone": 922146935,
  "pass": "Diqwer1234"
}
